spring:
  application:
    name: SpringBootTest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://162.14.71.103:3307/heima
    username: root
    password: 123

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    local-cache-scope: session

logging:
  level:
    com.example: debug
  pattern:
    dateformat:MM-dd HH:mm:ss:SSS
